Fix/docs
NikitaKit1998/datakyt pull request #30
Opened 2020-11-08 16:22 UTC by NikitaKit1998

# What does this PR do?

Removes mistakes or inconsistencies that appeared during the database creation. And also adds some information to README.md.

## Explanation

To fix mistakes and add new info.

2020-11-08 16:25 UTC, aartiukh requested changes

2020-11-08 16:25 UTC, aartiukh commented on docs/diagram.md
> +**name**              | CHAR(255) | NOT NULL                                     | stores the name of the equipment
why did you remove `FK` here?

2020-11-08 16:25 UTC, aartiukh commented on docs/diagram.md
> +**date_of_return** | DATE    | NULL | stores info when equipment was returned
please fix indentations in all tables

2020-11-08 20:53 UTC, NikitaKit1998 commented on docs/diagram.md
> +**name**              | CHAR(255) | NOT NULL                                     | stores the name of the equipment
Because the name is not `FK`

2020-11-08 20:56 UTC, paulzcooper commented on docs/diagram.md
> +**name**              | CHAR(255) | NOT NULL                                     | stores the name of the equipment
The field name should be `text`

2020-11-08 22:47 UTC, aartiukh approved these changes, later dismissed

2020-11-09 11:13 UTC, NikitaKit1998 commented on docs/diagram.md
> +**name**              | CHAR(255) | NOT NULL                                     | stores the name of the equipment
@paulzcooper fixed

2020-11-09 11:25 UTC, aartiukh approved these changes

2020-11-09 18:01 UTC, Alex-ty1 approved these changes

2020-11-09 19:55 UTC, paulzcooper approved these changes

2020-11-09 19:55 UTC, aartiukh requested changes
Why did you remove this file?
`docs/images/database.png`

2020-11-11 08:27 UTC, NikitaKit1998 commented
> Why did you remove this file?
> `docs/images/database.png`

Because I replaced it with another database.png

2020-11-12 21:21 UTC, aartiukh approved these changes

2020-11-12 21:21 UTC, merged