Added a method to write a name to qrcode [#29]
NikitaKit1998/datakyt pull request #33
Opened 2020-11-25 22:02 UTC by NikitaKit1998

# What does this PR do?

Added method that writes the full name on QR code PNG file.

## Issue reference

Fixes #29

## Explanation

Added the ability to write a name in qr code. The only disadvantage is that it is necessary to store the file with the font separately

2020-11-25 22:14 UTC, aartiukh requested changes

2020-11-25 22:14 UTC, aartiukh commented on examples/qr-generator-demo/qr-generator-demo.py
> +        font = ImageFont.truetype("arial.ttf", 20)
we can use a default font, see `ImageFont.load_default() `

2020-11-25 22:14 UTC, aartiukh commented on examples/qr-generator-demo/qr-generator-demo.py
> +        draw.text((140, 10), df["employee_name"][i], font=font)
Create variables for all magic numbers

2020-11-26 18:33 UTC, Alex-ty1 approved these changes, later dismissed

2020-11-28 12:53 UTC, aartiukh requested changes

2020-11-28 12:53 UTC, aartiukh commented on examples/qr-generator-demo/qr-generator-demo.py
> +    y=10
top_left_text_position = (140, 10)
move this definition closer to its usage, i.e. line 22

2020-11-28 12:53 UTC, aartiukh commented on examples/qr-generator-demo/qr-generator-demo.py
> +        font = ImageFont.load_default()
Remove

2020-11-28 12:53 UTC, aartiukh commented on examples/qr-generator-demo/qr-generator-demo.py
> +        draw.text((x, y), df["employee_name"][i], font=font)
```suggestion
        draw.text((x, y), df["employee_name"][i], font=ImageFont.load_default())
```

2020-11-28 15:45 UTC, NikitaKit1998 commented on examples/qr-generator-demo/qr-generator-demo.py
> +        font = ImageFont.load_default()
Removed

2020-11-28 15:45 UTC, NikitaKit1998 commented on examples/qr-generator-demo/qr-generator-demo.py
> +        draw.text((x, y), df["employee_name"][i], font=font)
Done

2020-11-28 16:19 UTC, aartiukh commented on examples/qr-generator-demo/qr-generator-demo.py
> +    y=10
@NikitaKit1998  ^^

2020-11-28 19:39 UTC, aartiukh approved these changes

2020-11-28 19:43 UTC, paulzcooper approved these changes

2020-11-28 19:44 UTC, merged