Added architecture database
NikitaKit1998/datakyt pull request #6
Opened 2020-10-20 20:12 UTC by NikitaKit1998

Prepare diagram

2020-10-23 19:23 UTC, NikitaKit1998 commented
Danke

2020-10-24 19:04 UTC, aartiukh requested changes

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +![image2.png](images/diagram.png)
Please increase font size

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**name** | TEXT    | -           | store name of software
constrains: not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**key_product**      | TEXT    | -           | stores product key of software
Not empty?
Rename `key_product` to `product_key` (don't forget to update on the diagram image)

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**expires_date**     | DATE    | -           | stores the expiration date of the license
constrains: `>= current date` or  `>= zero time` (1970)
Rename `expires_date` -> `date_of_expiry`

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**pick_up_date**        | DATE    | -           | stores info when license was picked up
Rename  `pick_up_date` ->  `fisrt_usage_date`

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**name**     | TEXT    | -           | stores name of furniture
Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**warranty** | INT     | -           | stores duration of warranty
Specify units (months)
constraints `>=0`

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**cost**     | INT     | -           | stores cost of furniture
Specify units (UAH)
constraints `>=0`

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**type** | CHAR(64) | -           | stores info of different types of furniture
constraints: Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**name**       | CHAR(65)    | -           | stores the full name of the employee
constraints: Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**email**      | CHAR(65)    | -           | stores employee email
constraints: Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**phone**      | VARCHAR(15) | -           | stores employee phone number
constraints: Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**warranty**          | INT           | -           | stores duration of warranty
constraints: >=0
specify units

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**cost**              | INT           | -           | stores equipment cost
constraints: >=0
specify units

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**status**            | CHAR(65)      | -           | stores information about the status of equipment
list all possible values
constraints: Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**phone**             | VARCHAR(15)   | -           | stores employee phone number
:open_mouth:

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**name** | CHAR(65) | -           | stores the name of the project
constraints: Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**name** | CHAR(255) | -           | stores the name of the office
constraints: Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**name** | CHAR(255) | -           | stores the name of the equipment type
constraints: Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**name**         | CHAR(255) | -           | stores the name of the equipment part
constraints: Not empty

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**name**          | CHAR(65) | -           | stores the full name of the employee
:open_mouth:

2020-10-24 19:04 UTC, aartiukh commented on docs/diagram.md
> +**pick_up_date**  | DATE     | -           | stores info when equipment was picked up
rename

2020-10-26 08:47 UTC, aartiukh approved these changes, later dismissed

2020-10-26 08:47 UTC, aartiukh commented on docs/diagram.md
> +**name** | TEXT    | NOT NULL           | store name of software
```suggestion
**name** | TEXT    | NOT NULL           | stores name of software
```

2020-10-26 08:47 UTC, aartiukh commented on docs/diagram.md
> +var name | type    | constraints | description
Please fix indentations in the tables.

2020-10-26 08:47 UTC, aartiukh commented on docs/diagram.md
> +**warranty** | INT     | NOT NULL, REAL(months)           | stores duration of warranty
```suggestion
**warranty** | INT     | NOT NULL, REAL (months)           | stores duration of warranty
```

2020-10-26 13:08 UTC, NikitaKit1998 commented on docs/diagram.md
> +var name | type    | constraints | description
fixed

2020-10-26 13:08 UTC, aartiukh approved these changes, later dismissed
LGTM

2020-10-26 14:10 UTC, NikitaKit1998 commented
Final fix in picture

2020-10-26 18:45 UTC, Alex-ty1 approved these changes, later dismissed

2020-10-26 20:00 UTC, aartiukh requested changes
Why two images files?
```
docs/images/database.png 
docs/images/diagram.png 
```
Remove unused one.

2020-10-26 20:28 UTC, aartiukh approved these changes

2020-10-26 20:45 UTC, Alex-ty1 approved these changes

2020-10-26 20:45 UTC, merged